version: '3.4'
services:
  webserver:
    build:
      args:
        email: 'application@sunmediatv.com'
        user: 'application'
      context: webserver
      dockerfile: Dockerfile
    container_name: webserver_lts
    volumes:
      - ./www/:/var/www/projects/
    environment:
      PHP_DATE_TIMEZONE: 'Europe/Madrid'
      XDEBUG_MODE : 'develop,debug,coverage'
      XDEBUG_START_WITH_REQUEST : 'yes'
    depends_on:
      - database
    ports:
      - "80:80"
      - "443:443"
      - "9001:9001"
    networks:
      network:
        ipv4_address: 174.16.4.1
  database:
    container_name: database
    image: mysql:8.0
    tty: true
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"
      - "./webserver/databases:/opt/databases"
    ports:
      - "33306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: 'root'
        MYSQL_DATABASE: 'symfony_db'
        MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      network:
        ipv4_address: 174.16.4.2
networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 174.16.4.0/16