version: '3.4'
services:
  webserver:
    build:
      args:
        email: 'application@sunmediatv.com'
        user: 'application'
      context: webserver
      dockerfile: Dockerfile
    container_name: webserver_lts
    volumes:
      - ./www/:/var/www/projects/
    environment:
      PHP_DATE_TIMEZONE: 'Europe/Madrid'
      XDEBUG_MODE : 'develop,debug,coverage'
      XDEBUG_START_WITH_REQUEST : 'yes'
    ports:
      - "80:80"
      - "443:443"
      - "9001:9001"
    networks:
      network:
        ipv4_address: 174.16.4.1
  database:
    container_name: database
    image: bitnami/postgresql
    volumes:
      - "./tmp/postgresql:/data"
    ports:
      - "5432:5432"
    environment:
      POSTGRESQL_USERNAME: 'root'
      POSTGRESQL_PASSWORD: 'root'
      POSTGRESQL_DATABASE: 'symfony_fast'
    networks:
      network:
        ipv4_address: 174.16.4.2
networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 174.16.4.0/16